version: '3.7'
services:
  database:
    image: postgres:15.3-alpine
    hostname: postgresql
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_database.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - sysnet
  system-permission-api:
    image: hmk/system-permission-api
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - sysnet
    environment:
      - JAVA_OPTIONS= -Xmx128m -Xms128m -Xss256k -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
    env_file:
      - 'variables.env'
volumes:
  postgresql:
  postgresql_data:
networks:
  sysnet:
    driver: bridge